#!/usr/bin/env node

require('ts-node').register()

// Include dependencies.
const fs = require('fs')
const Arweave = require('arweave/node')
const argv = require('yargs').argv
const smartweave = require('./src/index.ts')

// Set Arweave parameters from commandline or defaults.
const arweave_port = argv.arweavePort ? argv.arweavePort : 443
const arweave_host = argv.arweaveHost ? argv.arweaveHost : 'arweave.net'
const arweave_protocol = argv.arweaveProtocol ? argv.arweaveProtocol : 'https'

if(!argv.keyFile && !argv.walletFile) {
    console.log("ERROR: Please specify a wallet file to load using argument " +
        "'--key-file <PATH>'.")
    process.exit()
}

const raw_wallet = fs.readFileSync(argv.keyFile || argv.walletFile)
const wallet = JSON.parse(raw_wallet)

const arweave = Arweave.init({
    host: arweave_host, // Hostname or IP address for an Arweave node
    port: arweave_port,
    protocol: arweave_protocol
})

if(argv.create) {
    
    if(!argv.contractSrc && !argv.contractSrcTx) {
        console.log("ERROR: Please specify contract source bundle using argument " +
            "'--contract-src <PATH>' or --contract-src-tx <TX>.")
        process.exit()
    }

    if(!argv.initState) {
        console.log("ERROR: Please specify a file defining an initial state with " +
            "'--init-state <PATH>'.")
        process.exit()
    }

    if (argv.contractSrc) {
        // Create from a new source file. 
        const contractSrc = fs.readFileSync(argv.contractSrc)
        const minFee = argv.minFee ? argv.minFee : ''
        const initState = fs.readFileSync(argv.initState)

        smartweave.createContract(arweave, wallet, contractSrc, initState, minFee).then(
            (contractID) => {
                console.log("Contract created in TX: " + contractID)
            }
        )
    } else {
        // Create from existing tx. 
        const minFee = argv.minFee ? argv.minFee : ''
        const initState = fs.readFileSync(argv.initState)
        const contractSrcTx = argv.contractSrcTx;
        smartweave.createContractFromTx(arweave, wallet, contractSrcTx, initState, minFee).then(
            (contractID) => {
                console.log("Contract created in TX: " + contractID)
            }
        )
    }
    
}

if(argv.interact) {
    if(!argv.contract) {
        console.log("ERROR: Please specify a contract to interact with using " +
            "'--contract <TXID>'.")
        process.exit()
    }
    const contractID = argv.contract
    let input = undefined
    let dryRun = (argv.dryRun) ? true : false

    if(argv.inputFile) {
        input = fs.readFileSync(argv.inputFile)
    }
    else if(argv.input) {
        input = argv.input
    }
    else {
        console.log("ERROR: Please specify input to the contract using " +
            "'--input \"INPUT VAR\"' or '--input-file <FILE>'.")
        process.exit()
    }

    if (!dryRun) {
        smartweave.interactWrite(arweave, wallet, contractID, JSON.parse(input))
        .then((result) => {
                if(result) {
                    console.log("Result:\n" + result)
                }
                else {
                    console.log("ERROR: Contract execution on input failed.\n" +
                        "Input:\n" + input +
                        "\n")
                }
            }
        )
    }

    if (dryRun) {
        console.log(`Dry running`)
        smartweave.interactWriteDryRun(arweave, wallet, contractID, JSON.parse(input))
        .then((result) => {
            console.log(result)
        })
    } 
}

if(argv.getState) {
    if(!argv.contract) {
        console.log("ERROR: Please specify a contract to interact with using " +
            "'--contract <TXID>'.")
        process.exit()
    }
    const contractID = argv.contract

    smartweave.replayToState(arweave, contractID).then(
        (state) => {
            if(!state) {
                console.log("ERROR: Failed to get state for contract: " + contractID)
            }
        
            console.log(state)
        }
    )
}