name: csound_wasm
env:
  nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/3876561795a7111dac8fd4b71e0279e46b08eed8.tar.gz
on:
  push:
    branches:
      - feature/webaudio-csound
jobs:
  browser-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/pqndq1i9g5agiyr5iwwyl061s1c71kl6/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Build smartweave.js
        run: |
          yarn
          yarn build
      - name: Install test dependencies
        run: nix-shell --run 'exit 0'
      - name: Run the unit-tests
        continue-on-error: true # allow the reporter to report the failures
        run: yarn test:browser:ci
      - name: Fix the test report
        run: |
          cd $wasm_browser_dir
          nix-shell --pure
          mv tests/results.junit.xml tests/_results.junit.xml
          ex -s +'%s/<testsuite name=""[^>].\{-}>\n.*<\/testsuite>//ge' +%p +q! \
            tests/_results.junit.xml > tests/results.junit.xml
          rm tests/_results.junit.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/tests/*.junit.xml'
          fail_on_failure: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
